title: "Sai Chary Journal"
author: "Sai Chary"
email: "your-email@example.com"
description: "A high-performance, mobile-first Jekyll template for a personal portfolio and blog."
baseurl: "/1/"  # Ensure trailing slash for correct linking
url: "https://saicharyjournal.github.io"

# Repository (Ensures GitHub Pages works correctly)
repository: "SaiCharyJournal/saicharyjournal.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"  # Ensure correct remote theme

# SEO settings
google_analytics: "UA-XXXXXXXXX-X"  # Replace with your real ID
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Navbar sections
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Plugins (fixed duplication)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache  # Required for Minimal Mistakes

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Styling
minimal_mistakes_skin: "dark"  # Options: "default", "dark", "air", "aqua", etc.

# Footer Links (Corrected social links)
footer_links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/SaiCharyJournal"
  - label: "LinkedIn"
    icon: "fab fa-linkedin"
    url: "https://linkedin.com/in/your-profile"
  - label: "Twitter"
    icon: "fab fa-twitter"
    url: "https://twitter.com/your-profile"
