title: "Sai Chary Journal"
author: "Sai Chary"
email: "your-email@example.com"
description: "A high-performance, mobile-first Jekyll template for a personal portfolio and blog."
baseurl: "/1"  # Updated for correct deployment
url: "https://saicharyjournal.github.io"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes"  # Corrected theme setting

# SEO settings
google_analytics: "UA-XXXXXXXXX-X"  # Replace with your real ID
permalink: /:categories/:title/
timezone: Asia/Kolkata

# Social Links
social_links:
  github: "https://github.com/SaiCharyJournal"
  linkedin: "https://linkedin.com/in/your-profile"
  twitter: "https://twitter.com/your-profile"

# Navbar sections
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Plugins (fixed duplication)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Styling
minimal_mistakes_skin: "dark"  # Options: "default", "dark", "air", "aqua", etc.
