title: "Sai Chary Journal"
author: "Sai Chary"
email: "your-email@example.com"
description: "A high-performance, mobile-first Jekyll template for a personal portfolio and blog."
baseurl: "" # Leave blank unless your site is in a subdirectory
url: "https://saicharyjournal.github.io"

# Theme settings
theme: "minimal-mistakes-jekyll"

# SEO settings
google_analytics: "UA-XXXXXXXXX-X"  # Replace with your Google Analytics ID
permalink: /:categories/:title/
timezone: Asia/Kolkata  # Set your timezone

# Social Links
social_links:
  github: "https://github.com/SaiCharyJournal"
  linkedin: "https://linkedin.com/in/your-profile"
  twitter: "https://twitter.com/your-profile"

# Navbar sections
header_pages:
  - about.md
  - projects.md
  - blog.md
  - contact.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num/"

# Styling
minimal_mistakes_skin: "dark"  # Options: "default", "dark", "air", "aqua", etc.
